### ISSUE TITLE
Build Push Action

### ISSUE THREAD

**Issue by jreyesgar93** [optimizacion-2-2021-1-gh-classroom/practica-1-segunda-parte-yefovar#9]
La imagen de docker debe construirse y alojarse (build & push) automáticamente en dockerhub con un lanzamiento de un workflow de github vía github actions. Consultar las siguientes referencias para esto:

**Comment by Yalidt** [comment]
La imagen que apunta al Docker Hub es la que esta en la raiz del repositorio
